package com.mmrtr.lol.infra.persistence.match.repository;


import com.mmrtr.lol.infra.persistence.match.entity.MatchSummonerEntity;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@RequiredArgsConstructor
public class MatchSummonerRepositoryImpl {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final MatchSummonerJpaRepository matchSummonerJpaRepository;


    public List<MatchSummonerEntity> saveAll(List<MatchSummonerEntity> matchSummoners) {
        return matchSummonerJpaRepository.saveAll(matchSummoners);
    }


    public void bulkSave(List<MatchSummonerEntity> matchSummoners) {

        String sql = " INSERT INTO match_summoner (" +
                "summoner_id," +
                "match_id," +
                "riot_id_game_name," +
                "riot_id_tagline," +
                "puuid," +
                "profile_icon," +
                "summoner_name," +
                "participant_id," +
                "champ_level," +
                "champion_id," +
                "champion_name," +
                "lane," +
                "champ_experience," +
                "role," +
                "spell1casts," +
                "spell2casts," +
                "spell3casts," +
                "spell4casts," +
                "summoner1casts," +
                "summoner1id," +
                "summoner2casts," +
                "summoner2id," +
                "summoner_level," +
                "bounty_level," +
                "kills," +
                "assists," +
                "deaths," +
                "double_kills," +
                "triple_kills," +
                "quadra_kills," +
                "penta_kills," +
                "unreal_kills," +
                "champion_transform," +
                "gold_earned," +
                "gold_spent," +
                "items_purchased," +
                "consumables_purchased," +
                "neutral_minions_killed," +
                "total_minions_killed," +
                "objectives_stolen," +
                "objectives_stolen_assists," +
                "detector_wards_placed," +
                "sight_wards_bought_in_game," +
                "vision_score," +
                "vision_wards_bought_in_game," +
                "wards_killed," +
                "wards_placed," +
                "baron_kills," +
                "dragon_kills," +
                "first_blood_assist," +
                "first_blood_kill," +
                "first_tower_assist," +
                "first_tower_kill," +
                "inhibitor_kills," +
                "inhibitor_takedowns," +
                "inhibitors_lost," +
                "nexus_kills," +
                "nexus_takedowns," +
                "nexus_lost," +
                "turret_kills," +
                "turret_takedowns," +
                "turrets_lost," +
                "game_ended_in_early_surrender," +
                "game_ended_in_surrender," +
                "team_early_surrendered," +
                "team_position," +
                "team_id," +
                "win," +
                "time_played," +
                "individual_position," +
                "magic_damage_dealt," +
                "magic_damage_dealt_to_champions," +
                "magic_damage_taken," +
                "physical_damage_dealt," +
                "physical_damage_dealt_to_champions," +
                "physical_damage_taken," +
                "damage_dealt_to_buildings," +
                "damage_dealt_to_objectives," +
                "damage_dealt_to_turrets," +
                "damage_self_mitigated," +
                "total_damage_dealt," +
                "total_damage_dealt_to_champions," +
                "total_damage_shielded_on_teammates," +
                "total_damage_taken," +
                "true_damage_dealt," +
                "true_damage_dealt_to_champions," +
                "true_damage_taken," +
                "total_heal," +
                "total_heals_on_teammates," +
                "total_timeccdealt," +
                "total_time_spent_dead," +
                "total_units_healed," +
                "timeccing_others," +
                "killing_sprees," +
                "largest_critical_strike," +
                "largest_killing_spree," +
                "largest_multi_kill," +
                "longest_time_spent_living," +
                "all_in_pings," +
                "assist_me_pings," +
                "command_pings," +
                "eligible_for_progression," +
                "enemy_missing_pings," +
                "enemy_vision_pings," +
                "hold_pings," +
                "get_back_pings," +
                "need_vision_pings," +
                "on_my_way_pings," +
                "player_score0," +
                "player_score1," +
                "player_score2," +
                "player_score3," +
                "player_score4," +
                "player_score5," +
                "player_score6," +
                "player_score7," +
                "player_score8," +
                "player_score9," +
                "player_score10," +
                "player_score11," +
                "placement," +
                "player_augment1," +
                "player_augment2," +
                "player_augment3," +
                "player_augment4," +
                "player_subteam_id," +
                "push_pings," +
                "riot_id_name," +
                "subteam_placement," +
                "total_ally_jungle_minions_killed," +
                "total_enemy_jungle_minions_killed," +
                "vision_cleared_pings," +
                "item0," +
                "item1," +
                "item2," +
                "item3," +
                "item4," +
                "item5," +
                "item6," +
                "defense," +
                "flex," +
                "offense," +
                "primary_rune_id," +
                "primary_rune_ids," +
                "secondary_rune_id," +
                "secondary_rune_ids " +
                ") VALUES (" +
                ":summonerId," +
                ":matchId," +
                ":riotIdGameName," +
                ":riotIdTagline," +
                ":puuid," +
                ":profileIcon," +
                ":summonerName," +
                ":participantId," +
                ":champLevel," +
                ":championId," +
                ":championName," +
                ":lane," +
                ":champExperience," +
                ":role," +
                ":spell1Casts," +
                ":spell2Casts," +
                ":spell3Casts," +
                ":spell4Casts," +
                ":summoner1Casts," +
                ":summoner1Id," +
                ":summoner2Casts," +
                ":summoner2Id," +
                ":summonerLevel," +
                ":bountyLevel," +
                ":kills," +
                ":assists," +
                ":deaths," +
                ":doubleKills," +
                ":tripleKills," +
                ":quadraKills," +
                ":pentaKills," +
                ":unrealKills," +
                ":championTransform," +
                ":goldEarned," +
                ":goldSpent," +
                ":itemsPurchased," +
                ":consumablesPurchased," +
                ":neutralMinionsKilled," +
                ":totalMinionsKilled," +
                ":objectivesStolen," +
                ":objectivesStolenAssists," +
                ":detectorWardsPlaced," +
                ":sightWardsBoughtInGame," +
                ":visionScore," +
                ":visionWardsBoughtInGame," +
                ":wardsKilled," +
                ":wardsPlaced," +
                ":baronKills," +
                ":dragonKills," +
                ":firstBloodAssist," +
                ":firstBloodKill," +
                ":firstTowerAssist," +
                ":firstTowerKill," +
                ":inhibitorKills," +
                ":inhibitorTakedowns," +
                ":inhibitorsLost," +
                ":nexusKills," +
                ":nexusTakedowns," +
                ":nexusLost," +
                ":turretKills," +
                ":turretTakedowns," +
                ":turretsLost," +
                ":gameEndedInEarlySurrender," +
                ":gameEndedInSurrender," +
                ":teamEarlySurrendered," +
                ":teamPosition," +
                ":teamId," +
                ":win," +
                ":timePlayed," +
                ":individualPosition," +
                ":magicDamageDealt," +
                ":magicDamageDealtToChampions," +
                ":magicDamageTaken," +
                ":physicalDamageDealt," +
                ":physicalDamageDealtToChampions," +
                ":physicalDamageTaken," +
                ":damageDealtToBuildings," +
                ":damageDealtToObjectives," +
                ":damageDealtToTurrets," +
                ":damageSelfMitigated," +
                ":totalDamageDealt," +
                ":totalDamageDealtToChampions," +
                ":totalDamageShieldedOnTeammates," +
                ":totalDamageTaken," +
                ":trueDamageDealt," +
                ":trueDamageDealtToChampions," +
                ":trueDamageTaken," +
                ":totalHeal," +
                ":totalHealsOnTeammates," +
                ":totalTimeCCDealt," +
                ":totalTimeSpentDead," +
                ":totalUnitsHealed," +
                ":timeCCingOthers," +
                ":killingSprees," +
                ":largestCriticalStrike," +
                ":largestKillingSpree," +
                ":largestMultiKill," +
                ":longestTimeSpentLiving," +
                ":allInPings," +
                ":assistMePings," +
                ":commandPings," +
                ":eligibleForProgression," +
                ":enemyMissingPings," +
                ":enemyVisionPings," +
                ":holdPings," +
                ":getBackPings," +
                ":needVisionPings," +
                ":onMyWayPings," +
                ":playerScore0," +
                ":playerScore1," +
                ":playerScore2," +
                ":playerScore3," +
                ":playerScore4," +
                ":playerScore5," +
                ":playerScore6," +
                ":playerScore7," +
                ":playerScore8," +
                ":playerScore9," +
                ":playerScore10," +
                ":playerScore11," +
                ":placement," +
                ":playerAugment1," +
                ":playerAugment2," +
                ":playerAugment3," +
                ":playerAugment4," +
                ":playerSubteamId," +
                ":pushPings," +
                ":riotIdName," +
                ":subteamPlacement," +
                ":totalAllyJungleMinionsKilled," +
                ":totalEnemyJungleMinionsKilled," +
                ":visionClearedPings," +
                ":item0," +
                ":item1," +
                ":item2," +
                ":item3," +
                ":item4," +
                ":item5," +
                ":item6," +
                ":defense," +
                ":flex," +
                ":offense," +
                ":primaryRuneId," +
                ":primaryRuneIds," +
                ":secondaryRuneId," +
                ":secondaryRuneIds" +
                ") ON CONFLICT (puuid, match_id) DO NOTHING";

        SqlParameterSource[] params = matchSummoners.stream()
                .map(comment -> {
                    return new MapSqlParameterSource()
                            .addValue("summonerId", comment.getSummonerId())
                            .addValue("matchId", comment.getMatchId())
                            .addValue("riotIdGameName", comment.getRiotIdGameName())
                            .addValue("riotIdTagline", comment.getRiotIdTagline())
                            .addValue("puuid", comment.getPuuid())
                            .addValue("profileIcon", comment.getProfileIcon())
                            .addValue("summonerName", comment.getSummonerName())
                            .addValue("participantId", comment.getParticipantId())
                            .addValue("champLevel", comment.getChampLevel())
                            .addValue("championId", comment.getChampionId())
                            .addValue("championName", comment.getChampionName())
                            .addValue("lane", comment.getLane())
                            .addValue("champExperience", comment.getChampExperience())
                            .addValue("role", comment.getRole())
                            .addValue("spell1Casts", comment.getSpell1Casts())
                            .addValue("spell2Casts", comment.getSpell2Casts())
                            .addValue("spell3Casts", comment.getSpell3Casts())
                            .addValue("spell4Casts", comment.getSpell4Casts())
                            .addValue("summoner1Casts", comment.getSummoner1Casts())
                            .addValue("summoner1Id", comment.getSummoner1Id())
                            .addValue("summoner2Casts", comment.getSummoner2Casts())
                            .addValue("summoner2Id", comment.getSummoner2Id())
                            .addValue("summonerLevel", comment.getSummonerLevel())
                            .addValue("bountyLevel", comment.getBountyLevel())
                            .addValue("kills", comment.getKills())
                            .addValue("assists", comment.getAssists())
                            .addValue("deaths", comment.getDeaths())
                            .addValue("doubleKills", comment.getDoubleKills())
                            .addValue("tripleKills", comment.getTripleKills())
                            .addValue("quadraKills", comment.getQuadraKills())
                            .addValue("pentaKills", comment.getPentaKills())
                            .addValue("unrealKills", comment.getUnrealKills())
                            .addValue("championTransform", comment.getChampionTransform())
                            .addValue("goldEarned", comment.getGoldEarned())
                            .addValue("goldSpent", comment.getGoldSpent())
                            .addValue("itemsPurchased", comment.getItemsPurchased())
                            .addValue("consumablesPurchased", comment.getConsumablesPurchased())
                            .addValue("neutralMinionsKilled", comment.getNeutralMinionsKilled())
                            .addValue("totalMinionsKilled", comment.getTotalMinionsKilled())
                            .addValue("objectivesStolen", comment.getObjectivesStolen())
                            .addValue("objectivesStolenAssists", comment.getObjectivesStolenAssists())
                            .addValue("detectorWardsPlaced", comment.getDetectorWardsPlaced())
                            .addValue("sightWardsBoughtInGame", comment.getSightWardsBoughtInGame())
                            .addValue("visionScore", comment.getVisionScore())
                            .addValue("visionWardsBoughtInGame", comment.getVisionWardsBoughtInGame())
                            .addValue("wardsKilled", comment.getWardsKilled())
                            .addValue("wardsPlaced", comment.getWardsPlaced())
                            .addValue("baronKills", comment.getBaronKills())
                            .addValue("dragonKills", comment.getDragonKills())
                            .addValue("firstBloodAssist", comment.isFirstBloodAssist())
                            .addValue("firstBloodKill", comment.isFirstBloodKill())
                            .addValue("firstTowerAssist", comment.isFirstTowerAssist())
                            .addValue("firstTowerKill", comment.isFirstTowerKill())
                            .addValue("inhibitorKills", comment.getInhibitorKills())
                            .addValue("inhibitorTakedowns", comment.getInhibitorTakedowns())
                            .addValue("inhibitorsLost", comment.getInhibitorsLost())
                            .addValue("nexusKills", comment.getNexusKills())
                            .addValue("nexusTakedowns", comment.getNexusTakedowns())
                            .addValue("nexusLost", comment.getNexusLost())
                            .addValue("turretKills", comment.getTurretKills())
                            .addValue("turretTakedowns", comment.getTurretTakedowns())
                            .addValue("turretsLost", comment.getTurretsLost())
                            .addValue("gameEndedInEarlySurrender", comment.isGameEndedInEarlySurrender())
                            .addValue("gameEndedInSurrender", comment.isGameEndedInSurrender())
                            .addValue("teamEarlySurrendered", comment.isTeamEarlySurrendered())
                            .addValue("teamPosition", comment.getTeamPosition())
                            .addValue("teamId", comment.getTeamId())
                            .addValue("win", comment.isWin())
                            .addValue("timePlayed", comment.getTimePlayed())
                            .addValue("individualPosition", comment.getIndividualPosition())
                            .addValue("magicDamageDealt", comment.getMagicDamageDealt())
                            .addValue("magicDamageDealtToChampions", comment.getMagicDamageDealtToChampions())
                            .addValue("magicDamageTaken", comment.getMagicDamageTaken())
                            .addValue("physicalDamageDealt", comment.getPhysicalDamageDealt())
                            .addValue("physicalDamageDealtToChampions", comment.getPhysicalDamageDealtToChampions())
                            .addValue("physicalDamageTaken", comment.getPhysicalDamageTaken())
                            .addValue("damageDealtToBuildings", comment.getDamageDealtToBuildings())
                            .addValue("damageDealtToObjectives", comment.getDamageDealtToObjectives())
                            .addValue("damageDealtToTurrets", comment.getDamageDealtToTurrets())
                            .addValue("damageSelfMitigated", comment.getDamageSelfMitigated())
                            .addValue("totalDamageDealt", comment.getTotalDamageDealt())
                            .addValue("totalDamageDealtToChampions", comment.getTotalDamageDealtToChampions())
                            .addValue("totalDamageShieldedOnTeammates", comment.getTotalDamageShieldedOnTeammates())
                            .addValue("totalDamageTaken", comment.getTotalDamageTaken())
                            .addValue("trueDamageDealt", comment.getTrueDamageDealt())
                            .addValue("trueDamageDealtToChampions", comment.getTrueDamageDealtToChampions())
                            .addValue("trueDamageTaken", comment.getTrueDamageTaken())
                            .addValue("totalHeal", comment.getTotalHeal())
                            .addValue("totalHealsOnTeammates", comment.getTotalHealsOnTeammates())
                            .addValue("totalTimeCCDealt", comment.getTotalTimeCCDealt())
                            .addValue("totalTimeSpentDead", comment.getTotalTimeSpentDead())
                            .addValue("totalUnitsHealed", comment.getTotalUnitsHealed())
                            .addValue("timeCCingOthers", comment.getTimeCCingOthers())
                            .addValue("killingSprees", comment.getKillingSprees())
                            .addValue("largestCriticalStrike", comment.getLargestCriticalStrike())
                            .addValue("largestKillingSpree", comment.getLargestKillingSpree())
                            .addValue("largestMultiKill", comment.getLargestMultiKill())
                            .addValue("longestTimeSpentLiving", comment.getLongestTimeSpentLiving())
                            .addValue("allInPings", comment.getAllInPings())
                            .addValue("assistMePings", comment.getAssistMePings())
                            .addValue("commandPings", comment.getCommandPings())
                            .addValue("eligibleForProgression", comment.isEligibleForProgression())
                            .addValue("enemyMissingPings", comment.getEnemyMissingPings())
                            .addValue("enemyVisionPings", comment.getEnemyVisionPings())
                            .addValue("holdPings", comment.getHoldPings())
                            .addValue("getBackPings", comment.getGetBackPings())
                            .addValue("needVisionPings", comment.getNeedVisionPings())
                            .addValue("onMyWayPings", comment.getOnMyWayPings())
                            .addValue("playerScore0", comment.getPlayerScore0())
                            .addValue("playerScore1", comment.getPlayerScore1())
                            .addValue("playerScore2", comment.getPlayerScore2())
                            .addValue("playerScore3", comment.getPlayerScore3())
                            .addValue("playerScore4", comment.getPlayerScore4())
                            .addValue("playerScore5", comment.getPlayerScore5())
                            .addValue("playerScore6", comment.getPlayerScore6())
                            .addValue("playerScore7", comment.getPlayerScore7())
                            .addValue("playerScore8", comment.getPlayerScore8())
                            .addValue("playerScore9", comment.getPlayerScore9())
                            .addValue("playerScore10", comment.getPlayerScore10())
                            .addValue("playerScore11", comment.getPlayerScore11())
                            .addValue("placement", comment.getPlacement())
                            .addValue("playerAugment1", comment.getPlayerAugment1())
                            .addValue("playerAugment2", comment.getPlayerAugment2())
                            .addValue("playerAugment3", comment.getPlayerAugment3())
                            .addValue("playerAugment4", comment.getPlayerAugment4())
                            .addValue("playerSubteamId", comment.getPlayerSubteamId())
                            .addValue("pushPings", comment.getPushPings())
                            .addValue("riotIdName", comment.getRiotIdName())
                            .addValue("subteamPlacement", comment.getSubteamPlacement())
                            .addValue("totalAllyJungleMinionsKilled", comment.getTotalAllyJungleMinionsKilled())
                            .addValue("totalEnemyJungleMinionsKilled", comment.getTotalEnemyJungleMinionsKilled())
                            .addValue("visionClearedPings", comment.getVisionClearedPings())
                            .addValue("item0", comment.getItem().getItem0())
                            .addValue("item1", comment.getItem().getItem1())
                            .addValue("item2", comment.getItem().getItem2())
                            .addValue("item3", comment.getItem().getItem3())
                            .addValue("item4", comment.getItem().getItem4())
                            .addValue("item5", comment.getItem().getItem5())
                            .addValue("item6", comment.getItem().getItem6())
                            .addValue("defense", comment.getStatValue().getDefense())
                            .addValue("flex", comment.getStatValue().getFlex())
                            .addValue("offense", comment.getStatValue().getOffense())
                            .addValue("primaryRuneId", comment.getStyleValue().getPrimaryRuneId())
                            .addValue("primaryRuneIds", comment.getStyleValue().getPrimaryRuneIds())
                            .addValue("secondaryRuneId", comment.getStyleValue().getSecondaryRuneId())
                            .addValue("secondaryRuneIds", comment.getStyleValue().getSecondaryRuneIds())
                            ;
                })
                .toArray(SqlParameterSource[]::new);

        jdbcTemplate.batchUpdate(sql, params);
    }
}
