server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5555/postgres
    driver-class-name: org.postgresql.Driver
    username: ${PUSER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true

    show-sql: true
  kafka:
    consumer:
      bootstrap-servers: kafka:9094