spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,threaddump
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

lol:
  vt:
    executors:
      enabled: true
  backfill:
    range:
      start-id: ${BACKFILL_START_ID}
      end-id: ${BACKFILL_END_ID}
    chunk:
      size: ${BACKFILL_CHUNK_SIZE}
      parallelism: ${BACKFILL_PARALLELISM}
      fetch-size: ${BACKFILL_FETCH_SIZE}
    filter:
      season: ${BACKFILL_SEASON}
      queue-ids: ${BACKFILL_QUEUE_IDS}
    gcs:
      bucket: ${BACKFILL_GCS_BUCKET}

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - api-local.yml
      - persistence-local.yml
      - rabbitmq-local.yml
      - redis-local.yml
      - riot-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - api-dev.yml
      - persistence-dev.yml
      - rabbitmq-dev.yml
      - redis-dev.yml
      - riot-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - api-prod.yml
      - persistence-prod.yml
      - rabbitmq-prod.yml
      - redis-prod.yml
      - riot-prod.yml
