package com.mmrtr.lol.infra.persistence.match.repository;


import com.mmrtr.lol.infra.persistence.match.entity.MatchParticipantEntity;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@RequiredArgsConstructor
public class MatchSummonerRepositoryImpl {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final MatchSummonerJpaRepository matchSummonerJpaRepository;


    public List<MatchParticipantEntity> saveAll(List<MatchParticipantEntity> matchParticipants) {
        return matchSummonerJpaRepository.saveAll(matchParticipants);
    }


    public void bulkSave(List<MatchParticipantEntity> matchParticipants) {

        String sql = " INSERT INTO match_participant (" +
                "summoner_id," +
                "match_id," +
                "riot_id_game_name," +
                "riot_id_tagline," +
                "summoner_name," +
                "puuid," +
                "profile_icon," +
                "participant_id," +
                "champ_level," +
                "champion_id," +
                "champion_name," +
                "lane," +
                "champ_experience," +
                "role," +
                "spell1casts," +
                "spell2casts," +
                "spell3casts," +
                "spell4casts," +
                "summoner1casts," +
                "summoner1id," +
                "summoner2casts," +
                "summoner2id," +
                "summoner_level," +
                "bounty_level," +
                "kills," +
                "assists," +
                "deaths," +
                "double_kills," +
                "triple_kills," +
                "quadra_kills," +
                "penta_kills," +
                "unreal_kills," +
                "champion_transform," +
                "gold_earned," +
                "gold_spent," +
                "items_purchased," +
                "consumables_purchased," +
                "neutral_minions_killed," +
                "total_minions_killed," +
                "objectives_stolen," +
                "objectives_stolen_assists," +
                "detector_wards_placed," +
                "sight_wards_bought_in_game," +
                "vision_score," +
                "vision_wards_bought_in_game," +
                "wards_killed," +
                "wards_placed," +
                "baron_kills," +
                "dragon_kills," +
                "first_blood_assist," +
                "first_blood_kill," +
                "first_tower_assist," +
                "first_tower_kill," +
                "inhibitor_kills," +
                "inhibitor_takedowns," +
                "inhibitors_lost," +
                "nexus_kills," +
                "nexus_takedowns," +
                "nexus_lost," +
                "turret_kills," +
                "turret_takedowns," +
                "turrets_lost," +
                "game_ended_in_early_surrender," +
                "game_ended_in_surrender," +
                "team_early_surrendered," +
                "team_position," +
                "team_id," +
                "win," +
                "time_played," +
                "individual_position," +
                "magic_damage_dealt," +
                "magic_damage_dealt_to_champions," +
                "magic_damage_taken," +
                "physical_damage_dealt," +
                "physical_damage_dealt_to_champions," +
                "physical_damage_taken," +
                "damage_dealt_to_buildings," +
                "damage_dealt_to_objectives," +
                "damage_dealt_to_turrets," +
                "damage_dealt_to_epic_monsters," +
                "damage_self_mitigated," +
                "total_damage_dealt," +
                "total_damage_dealt_to_champions," +
                "total_damage_shielded_on_teammates," +
                "total_damage_taken," +
                "true_damage_dealt," +
                "true_damage_dealt_to_champions," +
                "true_damage_taken," +
                "total_heal," +
                "total_heals_on_teammates," +
                "total_timeccdealt," +
                "total_time_spent_dead," +
                "total_units_healed," +
                "timeccing_others," +
                "killing_sprees," +
                "largest_critical_strike," +
                "largest_killing_spree," +
                "largest_multi_kill," +
                "longest_time_spent_living," +
                "all_in_pings," +
                "assist_me_pings," +
                "basic_pings," +
                "command_pings," +
                "danger_pings," +
                "eligible_for_progression," +
                "enemy_missing_pings," +
                "enemy_vision_pings," +
                "hold_pings," +
                "get_back_pings," +
                "need_vision_pings," +
                "on_my_way_pings," +
                "push_pings," +
                "retreat_pings," +
                "vision_cleared_pings," +
                "player_score0," +
                "player_score1," +
                "player_score2," +
                "player_score3," +
                "player_score4," +
                "player_score5," +
                "player_score6," +
                "player_score7," +
                "player_score8," +
                "player_score9," +
                "player_score10," +
                "player_score11," +
                "placement," +
                "player_subteam_id," +
                "subteam_placement," +
                "player_augment1," +
                "player_augment2," +
                "player_augment3," +
                "player_augment4," +
                "player_augment5," +
                "player_augment6," +
                "total_ally_jungle_minions_killed," +
                "total_enemy_jungle_minions_killed," +
                "item0," +
                "item1," +
                "item2," +
                "item3," +
                "item4," +
                "item5," +
                "item6," +
                "stat_perk_defense," +
                "stat_perk_flex," +
                "stat_perk_offense," +
                "primary_style_id," +
                "primary_perk0," +
                "primary_perk1," +
                "primary_perk2," +
                "primary_perk3," +
                "sub_style_id," +
                "sub_perk0," +
                "sub_perk1," +
                "role_bound_item," +
                "tier," +
                "tier_rank," +
                "absolute_points " +
                ") VALUES (" +
                ":summonerId," +
                ":matchId," +
                ":riotIdGameName," +
                ":riotIdTagline," +
                ":summonerName," +
                ":puuid," +
                ":profileIcon," +
                ":participantId," +
                ":champLevel," +
                ":championId," +
                ":championName," +
                ":lane," +
                ":champExperience," +
                ":role," +
                ":spell1Casts," +
                ":spell2Casts," +
                ":spell3Casts," +
                ":spell4Casts," +
                ":summoner1Casts," +
                ":summoner1Id," +
                ":summoner2Casts," +
                ":summoner2Id," +
                ":summonerLevel," +
                ":bountyLevel," +
                ":kills," +
                ":assists," +
                ":deaths," +
                ":doubleKills," +
                ":tripleKills," +
                ":quadraKills," +
                ":pentaKills," +
                ":unrealKills," +
                ":championTransform," +
                ":goldEarned," +
                ":goldSpent," +
                ":itemsPurchased," +
                ":consumablesPurchased," +
                ":neutralMinionsKilled," +
                ":totalMinionsKilled," +
                ":objectivesStolen," +
                ":objectivesStolenAssists," +
                ":detectorWardsPlaced," +
                ":sightWardsBoughtInGame," +
                ":visionScore," +
                ":visionWardsBoughtInGame," +
                ":wardsKilled," +
                ":wardsPlaced," +
                ":baronKills," +
                ":dragonKills," +
                ":firstBloodAssist," +
                ":firstBloodKill," +
                ":firstTowerAssist," +
                ":firstTowerKill," +
                ":inhibitorKills," +
                ":inhibitorTakedowns," +
                ":inhibitorsLost," +
                ":nexusKills," +
                ":nexusTakedowns," +
                ":nexusLost," +
                ":turretKills," +
                ":turretTakedowns," +
                ":turretsLost," +
                ":gameEndedInEarlySurrender," +
                ":gameEndedInSurrender," +
                ":teamEarlySurrendered," +
                ":teamPosition," +
                ":teamId," +
                ":win," +
                ":timePlayed," +
                ":individualPosition," +
                ":magicDamageDealt," +
                ":magicDamageDealtToChampions," +
                ":magicDamageTaken," +
                ":physicalDamageDealt," +
                ":physicalDamageDealtToChampions," +
                ":physicalDamageTaken," +
                ":damageDealtToBuildings," +
                ":damageDealtToObjectives," +
                ":damageDealtToTurrets," +
                ":damageDealtToEpicMonsters," +
                ":damageSelfMitigated," +
                ":totalDamageDealt," +
                ":totalDamageDealtToChampions," +
                ":totalDamageShieldedOnTeammates," +
                ":totalDamageTaken," +
                ":trueDamageDealt," +
                ":trueDamageDealtToChampions," +
                ":trueDamageTaken," +
                ":totalHeal," +
                ":totalHealsOnTeammates," +
                ":totalTimeCCDealt," +
                ":totalTimeSpentDead," +
                ":totalUnitsHealed," +
                ":timeCCingOthers," +
                ":killingSprees," +
                ":largestCriticalStrike," +
                ":largestKillingSpree," +
                ":largestMultiKill," +
                ":longestTimeSpentLiving," +
                ":allInPings," +
                ":assistMePings," +
                ":basicPings," +
                ":commandPings," +
                ":dangerPings," +
                ":eligibleForProgression," +
                ":enemyMissingPings," +
                ":enemyVisionPings," +
                ":holdPings," +
                ":getBackPings," +
                ":needVisionPings," +
                ":onMyWayPings," +
                ":pushPings," +
                ":retreatPings," +
                ":visionClearedPings," +
                ":playerScore0," +
                ":playerScore1," +
                ":playerScore2," +
                ":playerScore3," +
                ":playerScore4," +
                ":playerScore5," +
                ":playerScore6," +
                ":playerScore7," +
                ":playerScore8," +
                ":playerScore9," +
                ":playerScore10," +
                ":playerScore11," +
                ":placement," +
                ":playerSubteamId," +
                ":subteamPlacement," +
                ":playerAugment1," +
                ":playerAugment2," +
                ":playerAugment3," +
                ":playerAugment4," +
                ":playerAugment5," +
                ":playerAugment6," +
                ":totalAllyJungleMinionsKilled," +
                ":totalEnemyJungleMinionsKilled," +
                ":item0," +
                ":item1," +
                ":item2," +
                ":item3," +
                ":item4," +
                ":item5," +
                ":item6," +
                ":statPerkDefense," +
                ":statPerkFlex," +
                ":statPerkOffense," +
                ":primaryStyleId," +
                ":primaryPerk0," +
                ":primaryPerk1," +
                ":primaryPerk2," +
                ":primaryPerk3," +
                ":subStyleId," +
                ":subPerk0," +
                ":subPerk1," +
                ":roleBoundItem," +
                ":tier," +
                ":tierRank," +
                ":absolutePoints" +
                ") ON CONFLICT (puuid, match_id) DO NOTHING";

        SqlParameterSource[] params = matchParticipants.stream()
                .map(entity -> {
                    return new MapSqlParameterSource()
                            .addValue("summonerId", entity.getSummonerId())
                            .addValue("matchId", entity.getMatchId())
                            .addValue("riotIdGameName", entity.getRiotIdGameName())
                            .addValue("riotIdTagline", entity.getRiotIdTagline())
                            .addValue("summonerName", entity.getSummonerName())
                            .addValue("puuid", entity.getPuuid())
                            .addValue("profileIcon", entity.getProfileIcon())
                            .addValue("participantId", entity.getParticipantId())
                            .addValue("champLevel", entity.getChampLevel())
                            .addValue("championId", entity.getChampionId())
                            .addValue("championName", entity.getChampionName())
                            .addValue("lane", entity.getLane())
                            .addValue("champExperience", entity.getChampExperience())
                            .addValue("role", entity.getRole())
                            .addValue("spell1Casts", entity.getSpell1Casts())
                            .addValue("spell2Casts", entity.getSpell2Casts())
                            .addValue("spell3Casts", entity.getSpell3Casts())
                            .addValue("spell4Casts", entity.getSpell4Casts())
                            .addValue("summoner1Casts", entity.getSummoner1Casts())
                            .addValue("summoner1Id", entity.getSummoner1Id())
                            .addValue("summoner2Casts", entity.getSummoner2Casts())
                            .addValue("summoner2Id", entity.getSummoner2Id())
                            .addValue("summonerLevel", entity.getSummonerLevel())
                            .addValue("bountyLevel", entity.getBountyLevel())
                            .addValue("kills", entity.getKills())
                            .addValue("assists", entity.getAssists())
                            .addValue("deaths", entity.getDeaths())
                            .addValue("doubleKills", entity.getDoubleKills())
                            .addValue("tripleKills", entity.getTripleKills())
                            .addValue("quadraKills", entity.getQuadraKills())
                            .addValue("pentaKills", entity.getPentaKills())
                            .addValue("unrealKills", entity.getUnrealKills())
                            .addValue("championTransform", entity.getChampionTransform())
                            .addValue("goldEarned", entity.getGoldEarned())
                            .addValue("goldSpent", entity.getGoldSpent())
                            .addValue("itemsPurchased", entity.getItem().getItemsPurchased())
                            .addValue("consumablesPurchased", entity.getItem().getConsumablesPurchased())
                            .addValue("neutralMinionsKilled", entity.getNeutralMinionsKilled())
                            .addValue("totalMinionsKilled", entity.getTotalMinionsKilled())
                            .addValue("objectivesStolen", entity.getObjectivesStolen())
                            .addValue("objectivesStolenAssists", entity.getObjectivesStolenAssists())
                            .addValue("detectorWardsPlaced", entity.getDetectorWardsPlaced())
                            .addValue("sightWardsBoughtInGame", entity.getSightWardsBoughtInGame())
                            .addValue("visionScore", entity.getVisionScore())
                            .addValue("visionWardsBoughtInGame", entity.getVisionWardsBoughtInGame())
                            .addValue("wardsKilled", entity.getWardsKilled())
                            .addValue("wardsPlaced", entity.getWardsPlaced())
                            .addValue("baronKills", entity.getBaronKills())
                            .addValue("dragonKills", entity.getDragonKills())
                            .addValue("firstBloodAssist", entity.isFirstBloodAssist())
                            .addValue("firstBloodKill", entity.isFirstBloodKill())
                            .addValue("firstTowerAssist", entity.isFirstTowerAssist())
                            .addValue("firstTowerKill", entity.isFirstTowerKill())
                            .addValue("inhibitorKills", entity.getInhibitorKills())
                            .addValue("inhibitorTakedowns", entity.getInhibitorTakedowns())
                            .addValue("inhibitorsLost", entity.getInhibitorsLost())
                            .addValue("nexusKills", entity.getNexusKills())
                            .addValue("nexusTakedowns", entity.getNexusTakedowns())
                            .addValue("nexusLost", entity.getNexusLost())
                            .addValue("turretKills", entity.getTurretKills())
                            .addValue("turretTakedowns", entity.getTurretTakedowns())
                            .addValue("turretsLost", entity.getTurretsLost())
                            .addValue("gameEndedInEarlySurrender", entity.isGameEndedInEarlySurrender())
                            .addValue("gameEndedInSurrender", entity.isGameEndedInSurrender())
                            .addValue("teamEarlySurrendered", entity.isTeamEarlySurrendered())
                            .addValue("teamPosition", entity.getTeamPosition())
                            .addValue("teamId", entity.getTeamId())
                            .addValue("win", entity.isWin())
                            .addValue("timePlayed", entity.getTimePlayed())
                            .addValue("individualPosition", entity.getIndividualPosition())
                            .addValue("magicDamageDealt", entity.getMagicDamageDealt())
                            .addValue("magicDamageDealtToChampions", entity.getMagicDamageDealtToChampions())
                            .addValue("magicDamageTaken", entity.getMagicDamageTaken())
                            .addValue("physicalDamageDealt", entity.getPhysicalDamageDealt())
                            .addValue("physicalDamageDealtToChampions", entity.getPhysicalDamageDealtToChampions())
                            .addValue("physicalDamageTaken", entity.getPhysicalDamageTaken())
                            .addValue("damageDealtToBuildings", entity.getDamageDealtToBuildings())
                            .addValue("damageDealtToObjectives", entity.getDamageDealtToObjectives())
                            .addValue("damageDealtToTurrets", entity.getDamageDealtToTurrets())
                            .addValue("damageDealtToEpicMonsters", entity.getDamageDealtToEpicMonsters())
                            .addValue("damageSelfMitigated", entity.getDamageSelfMitigated())
                            .addValue("totalDamageDealt", entity.getTotalDamageDealt())
                            .addValue("totalDamageDealtToChampions", entity.getTotalDamageDealtToChampions())
                            .addValue("totalDamageShieldedOnTeammates", entity.getTotalDamageShieldedOnTeammates())
                            .addValue("totalDamageTaken", entity.getTotalDamageTaken())
                            .addValue("trueDamageDealt", entity.getTrueDamageDealt())
                            .addValue("trueDamageDealtToChampions", entity.getTrueDamageDealtToChampions())
                            .addValue("trueDamageTaken", entity.getTrueDamageTaken())
                            .addValue("totalHeal", entity.getTotalHeal())
                            .addValue("totalHealsOnTeammates", entity.getTotalHealsOnTeammates())
                            .addValue("totalTimeCCDealt", entity.getTotalTimeCCDealt())
                            .addValue("totalTimeSpentDead", entity.getTotalTimeSpentDead())
                            .addValue("totalUnitsHealed", entity.getTotalUnitsHealed())
                            .addValue("timeCCingOthers", entity.getTimeCCingOthers())
                            .addValue("killingSprees", entity.getKillingSprees())
                            .addValue("largestCriticalStrike", entity.getLargestCriticalStrike())
                            .addValue("largestKillingSpree", entity.getLargestKillingSpree())
                            .addValue("largestMultiKill", entity.getLargestMultiKill())
                            .addValue("longestTimeSpentLiving", entity.getLongestTimeSpentLiving())
                            .addValue("allInPings", entity.getAllInPings())
                            .addValue("assistMePings", entity.getAssistMePings())
                            .addValue("basicPings", entity.getBasicPings())
                            .addValue("commandPings", entity.getCommandPings())
                            .addValue("dangerPings", entity.getDangerPings())
                            .addValue("eligibleForProgression", entity.isEligibleForProgression())
                            .addValue("enemyMissingPings", entity.getEnemyMissingPings())
                            .addValue("enemyVisionPings", entity.getEnemyVisionPings())
                            .addValue("holdPings", entity.getHoldPings())
                            .addValue("getBackPings", entity.getGetBackPings())
                            .addValue("needVisionPings", entity.getNeedVisionPings())
                            .addValue("onMyWayPings", entity.getOnMyWayPings())
                            .addValue("pushPings", entity.getPushPings())
                            .addValue("retreatPings", entity.getRetreatPings())
                            .addValue("visionClearedPings", entity.getVisionClearedPings())
                            .addValue("playerScore0", entity.getPlayerScore0())
                            .addValue("playerScore1", entity.getPlayerScore1())
                            .addValue("playerScore2", entity.getPlayerScore2())
                            .addValue("playerScore3", entity.getPlayerScore3())
                            .addValue("playerScore4", entity.getPlayerScore4())
                            .addValue("playerScore5", entity.getPlayerScore5())
                            .addValue("playerScore6", entity.getPlayerScore6())
                            .addValue("playerScore7", entity.getPlayerScore7())
                            .addValue("playerScore8", entity.getPlayerScore8())
                            .addValue("playerScore9", entity.getPlayerScore9())
                            .addValue("playerScore10", entity.getPlayerScore10())
                            .addValue("playerScore11", entity.getPlayerScore11())
                            .addValue("placement", entity.getArena().getPlacement())
                            .addValue("playerSubteamId", entity.getArena().getPlayerSubteamId())
                            .addValue("subteamPlacement", entity.getArena().getSubteamPlacement())
                            .addValue("playerAugment1", entity.getArena().getPlayerAugment1())
                            .addValue("playerAugment2", entity.getArena().getPlayerAugment2())
                            .addValue("playerAugment3", entity.getArena().getPlayerAugment3())
                            .addValue("playerAugment4", entity.getArena().getPlayerAugment4())
                            .addValue("playerAugment5", entity.getArena().getPlayerAugment5())
                            .addValue("playerAugment6", entity.getArena().getPlayerAugment6())
                            .addValue("totalAllyJungleMinionsKilled", entity.getTotalAllyJungleMinionsKilled())
                            .addValue("totalEnemyJungleMinionsKilled", entity.getTotalEnemyJungleMinionsKilled())
                            .addValue("item0", entity.getItem().getItem0())
                            .addValue("item1", entity.getItem().getItem1())
                            .addValue("item2", entity.getItem().getItem2())
                            .addValue("item3", entity.getItem().getItem3())
                            .addValue("item4", entity.getItem().getItem4())
                            .addValue("item5", entity.getItem().getItem5())
                            .addValue("item6", entity.getItem().getItem6())
                            .addValue("statPerkDefense", entity.getPerk().getStatPerkDefense())
                            .addValue("statPerkFlex", entity.getPerk().getStatPerkFlex())
                            .addValue("statPerkOffense", entity.getPerk().getStatPerkOffense())
                            .addValue("primaryStyleId", entity.getPerk().getPrimaryStyleId())
                            .addValue("primaryPerk0", entity.getPerk().getPrimaryPerk0())
                            .addValue("primaryPerk1", entity.getPerk().getPrimaryPerk1())
                            .addValue("primaryPerk2", entity.getPerk().getPrimaryPerk2())
                            .addValue("primaryPerk3", entity.getPerk().getPrimaryPerk3())
                            .addValue("subStyleId", entity.getPerk().getSubStyleId())
                            .addValue("subPerk0", entity.getPerk().getSubPerk0())
                            .addValue("subPerk1", entity.getPerk().getSubPerk1())
                            .addValue("roleBoundItem", entity.getRoleBoundItem())
                            .addValue("tier", entity.getTier())
                            .addValue("tierRank", entity.getTierRank())
                            .addValue("absolutePoints", entity.getAbsolutePoints())
                            ;
                })
                .toArray(SqlParameterSource[]::new);

        jdbcTemplate.batchUpdate(sql, params);
    }
}
