bootJar.enabled = false
jar.enabled = true

dependencies {
    implementation project(':module:domain:champion')
    implementation project(':module:domain:league')
    implementation project(':core:domain')
    implementation project(':module:shared')
    implementation project(':module:common')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}
