spring:
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,threaddump
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

lol:
  vt:
    executors:
      enabled: true
