spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://lol-postgres:5432/postgres?reWriteBatchedInserts=true&tcpKeepAlive=true
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 15
      leak-detection-threshold: 300000
      max-lifetime: 1500000
      keepalive-time: 300000
